export {default as breadcrumbImg1} from "./banner1.jpg"
export {default as breadcrumbImg2} from "./banner2.jpg"
export {default as breadcrumbImg3} from "./breadcrumbImg3.webp"
export {default as hero1} from "./hero.gif"
export {default as hero2} from "./hero3.gif"
export {default as dance1} from "./break.jpg"
export {default as dance2} from "./hiphup.jpg"
export {default as dance3} from "./boolywood.jpg"
export {default as fitness1} from "./arobic.jpg"
export {default as fitness2} from "./acrobatik.jpg"
export {default as fitness3} from "./zoomba.jpg"
export {default as contactImg} from "./contact2.jpg"


export {default as galleryImg} from "./gallery.jpg"
export {default as galleryImg1} from "./gallery1.jpg"
export {default as galleryImg2} from "./gallery2.jpg"
export {default as galleryImg3} from "./gallery3.jpg"
export {default as galleryImg4} from "./gallery4.jpeg"
export {default as galleryImg5} from "./gallery5.jpg"